<a href="https://colab.research.google.com/github/ItsArnavRathi/Smart-student-feedback-insight-system/blob/main/Smart_Student_Feedback_Insight_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /usr/local/lib/python3.12/dist-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.2.25)

In [ ]:
import kagglehub

# Download dataset
path = kagglehub.dataset_download("omarsobhy14/university-students-complaints-and-reports")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/omarsobhy14/university-students-complaints-and-reports/2.archive...

100%|██████████| 38.8k/38.8k [00:00<00:00, 16.9MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/omarsobhy14/university-students-complaints-and-reports/versions/2

In [ ]:
import os

print(os.listdir(path))

['Datasetprojpowerbi.csv']

In [ ]:
import pandas as pd

file_path = path + "/Datasetprojpowerbi.csv"   # change this after checking
df = pd.read_csv(file_path)

df.head()

,Genre,Reports,Age,Gpa,Year,Count,Gender,Nationality
0,Academic Support and Resources,The limited access to research databases and m...,27,2.18,2,1,M,Egypt
1,Academic Support and Resources,I'm having trouble finding the course material...,23,3.11,2,1,F,Egypt
2,Academic Support and Resources,It's frustrating to have limited access to res...,20,3.68,2,1,F,Egypt
3,Academic Support and Resources,I'm really struggling in one of my classes but...,20,1.30,2,1,F,Egypt
4,Academic Support and Resources,I am really struggling with understanding the...,26,2.50,2,1,F,Egypt

In [ ]:
df = pd.read_csv(file_path)
print(df.columns)

Index(['Genre', 'Reports', 'Age', 'Gpa', 'Year', 'Count', 'Gender',
       'Nationality'],
      dtype='object')

In [ ]:
for col in df.columns:
    print(col)
    print(df[col].head(3))
    print("--------")

Genre
0    Academic Support and Resources
1    Academic Support and Resources
2    Academic Support and Resources
Name: Genre, dtype: object
--------
Reports
0    The limited access to research databases and m...
1    I'm having trouble finding the course material...
2    It's frustrating to have limited access to res...
Name: Reports, dtype: object
--------
Age
0    27
1    23
2    20
Name: Age, dtype: int64
--------
Gpa
0    2.18
1    3.11
2    3.68
Name: Gpa, dtype: float64
--------
Year
0    2
1    2
2    2
Name: Year, dtype: int64
--------
Count
0    1
1    1
2    1
Name: Count, dtype: int64
--------
Gender
0    M
1    F
2    F
Name: Gender, dtype: object
--------
Nationality
0    Egypt
1    Egypt
2    Egypt
Name: Nationality, dtype: object
--------

In [ ]:
df = df[['Reports']]

In [ ]:
df = df.dropna()

In [ ]:
df = df.head(100)

In [ ]:
df.shape
df.columns

Index(['Reports'], dtype='object')

In [ ]:
df.head(5)

                                             Reports
0  The limited access to research databases and m...
1  I'm having trouble finding the course material...
2  It's frustrating to have limited access to res...
3  I'm really struggling in one of my classes but...
4   I am really struggling with understanding the...

In [ ]:
df.isnull().sum()

Reports    0
dtype: int64

In [ ]:
df['Complaint_length'] = df['Reports'].apply(len)
df['Complaint_length'].describe()

count    1005.000000
mean      132.808955
std        50.174847
min        26.000000
25%       104.000000
50%       124.000000
75%       153.000000
max       386.000000
Name: Complaint_length, dtype: float64

In [ ]:
df = df.dropna(subset=['Reports'])
df = df[df['Reports'].str.strip() != ""]

In [ ]:
df = df[df['Reports'].str.len() > 10]

In [ ]:
from google.colab import userdata

# Replace 'YOUR_SE' with the exact name you used in the 🔑 tab
api_key = userdata.get('GOOGLE_API_KEY')

In [ ]:
!pip install -q google-generativeai

In [ ]:
for m in genai.list_models():
    print(m.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-2.5-flash-lite-preview-09-2025
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/gemini-robotics-er-1.5-preview
models/gemini-2.5-computer-use-preview-10-2025
models/deep-research-pro-preview-12-2025
models/gemini-embedding-001
models/gemini-embedding-2-preview
models/aqa
models/imagen-4.0-generate-001
models/imagen-4.0-ultra-generate-001
models/imagen-4.0-fast-generate-001
models/veo-2.0-generate-001
models/veo-3.0-generate-001
models/veo-3.0-fast-generate-001
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025
models/gemini-2.5-flash-native-audio-preview-12-2025

In [1]:
!pip install textblob
!pip install wordcloud

Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in /usr/local/lib/python3.12/dist-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (4.67.3)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.12/dist-packages (1.9.6)
Requirement already satisfied: numpy>=1.19.3 in /usr/local/lib/python3.12/dist-packages (from wordcloud) (2.0.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from wordcloud) (11.3.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from wordcloud) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)

In [2]:
import pandas as pd
from textblob import TextBlob
import matplotlib.pyplot as plt
import seaborn as sns