<a href="https://colab.research.google.com/github/ItsArnavRathi/Smart-student-feedback-insight-system/blob/main/STUDENT%20FEEDBACK%20SYSTEM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /usr/local/lib/python3.12/dist-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.2.25)

In [2]:
import kagglehub

# Download dataset
path = kagglehub.dataset_download("omarsobhy14/university-students-complaints-and-reports")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/omarsobhy14/university-students-complaints-and-reports/2.archive...

100%|██████████| 38.8k/38.8k [00:00<00:00, 33.4MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/omarsobhy14/university-students-complaints-and-reports/versions/2

In [3]:
import os

print(os.listdir(path))

['Datasetprojpowerbi.csv']

In [4]:
import pandas as pd

file_path = path + "/Datasetprojpowerbi.csv"   # change this after checking
df = pd.read_csv(file_path)

df.head()

,Genre,Reports,Age,Gpa,Year,Count,Gender,Nationality
0,Academic Support and Resources,The limited access to research databases and m...,27,2.18,2,1,M,Egypt
1,Academic Support and Resources,I'm having trouble finding the course material...,23,3.11,2,1,F,Egypt
2,Academic Support and Resources,It's frustrating to have limited access to res...,20,3.68,2,1,F,Egypt
3,Academic Support and Resources,I'm really struggling in one of my classes but...,20,1.30,2,1,F,Egypt
4,Academic Support and Resources,I am really struggling with understanding the...,26,2.50,2,1,F,Egypt

In [8]:
df = df[['Reports']]

In [9]:
df = df.dropna()

In [10]:
df = df.head(100)

In [11]:
df.shape
df.columns

Index(['Reports'], dtype='object')

In [12]:
df.head(5)

                                             Reports
0  The limited access to research databases and m...
1  I'm having trouble finding the course material...
2  It's frustrating to have limited access to res...
3  I'm really struggling in one of my classes but...
4   I am really struggling with understanding the...

In [13]:
df.isnull().sum()

Reports    0
dtype: int64

In [14]:
df['Complaint_length'] = df['Reports'].apply(len)
df['Complaint_length'].describe()

count    100.000000
mean     136.180000
std       24.988636
min       67.000000
25%      118.750000
50%      134.000000
75%      153.250000
max      198.000000
Name: Complaint_length, dtype: float64

In [15]:
df = df.dropna(subset=['Reports'])
df = df[df['Reports'].str.strip() != ""]

In [16]:
df = df[df['Reports'].str.len() > 10]